core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
# from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('accounts/', include('allauth.urls')),
	path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('profile/', include('users.urls', namespace='profile')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


users/urls.py
from django.urls import path
from users.views import (
    profile_view,
    edit_profile_view,
)

app_name = 'users'

urlpatterns = [
    path('<username>/',profile_view, name="view"),
    path('<username>/edit/',edit_profile_view, name="edit"),
]

users/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from django.dispatch.dispatcher import receiver
from django.db.models.signals import post_save
from django.contrib.auth.signals import user_logged_in, user_logged_out
from django.conf import settings
import os

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    # print("url:", instance.image.url)
    # print("path:", instance.image.path)
    # img_path = '{0}/{1}/profile_pic.png'.format(settings.MEDIA_ROOT, instance.user.username)
    # print("Image_path: ", img_path)
    # if os.path.isfile(img_path):
        # print("There's a file")
    #     os.remove(img_path)
    # print("user_directory_path: instance:", instance, "instance.pk:", instance.pk, "instance.user.pk:",instance.user.pk)
    ext = instance.extension()
    # file_upload_dir = os.path.join(settings.MEDIA_ROOT, instance.user.username)
    # ext = instance.extension()
    # if os.path.exists(file_upload_dir):
    #     import shutil
    #     shutil.rmtree(file_upload_dir)
    # return os.path.join(file_upload_dir, filename, ext)
    return '{0}/{1}{2}'.format(instance.user.username, "profile_pic", ext)

# def user_name(instance):
#     # get instance username
#     return '{0}'.format(instance.user.username)

class Profile(models.Model):
    '''
    Profile model to keep user profile data extend the account db
    user: requires a User from allauth account tobe chosen and set as primary key
    one-to-one model simplified means only one Profile can be tied to one User
    image: to set the profile image
    is_online: use to verify if person is online
    '''
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True) # on_delete=models.CASCADE Delete profile when user is deleted
    image = models.ImageField(default='default.jpg', upload_to=user_directory_path)
    is_online = models.BooleanField(default=False)
    nick_name = models.CharField(max_length=20, blank=True)
    hide_email = models.BooleanField(default=False)

    # def save(self, *args, **kwargs):
    #     if self.nick_name is None:
    #         self.nick_name = self.user.username
    #     super(Profile,self).save(*args,**kwargs)

    def __str__(self):
        return f'{self.user.username} Profile' #show how we want it to be display

    def extension(self):
        name, extension = os.path.splitext(self.image.name)
        return extension
    
@receiver(post_save, sender=User)
def init_profile(sender, instance, created, **kwargs):
    '''
    Signal when a post is received
    Automatically create a profile object(DB) and set user
    '''
    print(sender, instance, created)
    if created:
        Profile.objects.create(user=instance, nick_name=instance)
    
@receiver(user_logged_in)
def log_user_login(sender, request, user, **kwargs):
    '''
    Signal when a login happens
    Automatically update is_online field to True
    '''
    # print(user, sender, request)
    Profile.objects.all().filter(user=user).update(is_online=True)

@receiver(user_logged_out)
def log_user_logout(sender, request, user, **kwargs):
    '''
    Signal when a login happens
    Automatically update is_online field to False
    '''
    Profile.objects.all().filter(user=user).update(is_online=False)

users/forms.py
from django import forms
# from django.contrib.auth.forms import UserCreationForm
# from django.contrib.auth import authenticate
from users.models import Profile
from django.conf import settings

# def _language(content):


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('image','hide_email','nick_name')
    def save(self, commit=True):
        profile = super(ProfileUpdateForm, self).save(commit=False)
        profile.image = self.cleaned_data['image']
        profile.nick_name = self.cleaned_data['nick_name']
        profile.hide_email = self.cleaned_data['hide_email']
        if commit:
            profile.save()
        return profile

users/views.py
from django.shortcuts import render, redirect
from django.http import response
from django.contrib.auth import login, authenticate, logout
from django.conf import settings


from users.models import Profile
from users.forms import ProfileUpdateForm
from django.http import HttpResponse
import json

# Create your views here.
def profile_view(request, *args, **kwargs):
    '''
    Check if is_self (bool)
        if is_friend (bool)
            -1: no_request_sent
             0: They sent request
             1: you sent request
    '''
    context ={} 
    print ("request: ", request)
    username = kwargs.get('username')
    print("username: ", username)
    try:
        # print()
        profile = Profile.objects.get(user__username=username)
        # print("profile:", profile)
    except Profile.DoesNotExist:
        return HttpResponse("profile does not exist")
    if profile:
        # print(profile.user.username, profile.user.email)
        context["username"] = profile.user.username
        context["email"] = profile.user.email
        context["profile_image"] = profile.image.url

        # Define template variable
        is_self = True
        is_friend = False
        hide_email = profile.hide_email
        user = request.user
        # print(user,profile)
        if user.is_authenticated and user != profile.user:
            is_self = False
        elif not user.is_authenticated:
            is_self = False
        # if kwargs.get('JSON'):
        #     is_JSON = True
        # else:
        is_JSON = bool(request.GET.get('JSON'))
        context["is_self"] = is_self
        context["hide_email"] = hide_email
        context["is_friend"] = is_friend
        context["BASE_URL"] = settings.BASE_URL

        if is_JSON is False:
            return render(request, "profile.html", context)
        else:
        # To get JSON data about profile
            return HttpResponse(json.dumps(context), content_type="application/json")

def edit_profile_view(request, *args, **kwargs):
    if not request.user.is_authenticated:
        return redirect("/")
    username = kwargs.get('username')
    try:
        profile = Profile.objects.get(user__username=username)
        print("profile edit profile.user.pk:", profile.user.pk)
        print("profile edit profile.user:", profile.user)
    except Profile.DoesNotExist:
        print("user does not exist")
        return HttpResponse("profile does not exist")
    user = request.user
    print("user:", profile.image.url)
    if user != profile.user:
        return HttpResponse("Unable to edit someone elses profile")
    context = {}
    if request.POST:
        form = ProfileUpdateForm(request.POST, request.FILES, instance=profile)
        print("Instance is: ", request.user)
        if form.is_valid():
            profile1 = Profile.objects.get(user__username=username)
            print("form:", profile1.image.url)
            if profile1.image.url != "/media/default.jpg":
                profile1.image.delete()
            form.save()
            print("form is saved")
            return redirect("profile:view", username=profile.user)
        else:
            form = ProfileUpdateForm(request.POST, instance=request.user,
                initial = {
                    # "id": profile.user.pk,
                    "image": profile.image,
                    "nick_name": profile.nick_name,
                    "hide_email": profile.hide_email,
                }
            )
            context['form'] = form
    else:
        form = ProfileUpdateForm(
                initial = {
                    # "id": profile.user.pk,
                    "image": profile.image,
                    "nick_name": profile.nick_name,
                    "hide_email": profile.hide_email,
                }
            )
        context['form'] = form
    context['DATA_UPLOAD_MAX_MEMORY_SIZE'] = settings.DATA_UPLOAD_MAX_MEMORY_SIZE
    return render(request, "edit.html", context)

users/templates/edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<style type="text/css">
	.image-container{
		max-width: 250px;
		height: auto;
		position: relative;
	}
	.field-heading{
		color: #737373;
	}
	#id_confirm{
		color: green;
	}
	#id_confirm:hover {
		opacity: 0.3;
	}
	#id_cancel:hover {
		opacity: 0.3;
	}
	#id_cancel{
		color: red;
	}
	.material-icons{
		font-size: 30px;
	}
	.material-icons:hover{
		cursor: pointer;
	}
    .middle{
        vertical-align: middle;
    }
</style>



<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card profile-card">
		  <div class="card-body">
		  	<div class="d-flex flex-column justify-content-center p-4">
		  		<div class="mb-2" id="id_image_crop_confirm">
		  			<span id="id_cancel" class="material-icons">cancel</span>
		  			<span id="id_confirm" class="material-icons">check</span>
		  		</div>
		  		<div class="image-container" id="id_image_container">
	  				<img class="rounded" id="id_profile_image_display" src="{{form.initial.image.url}}">
					<div class="middle" id="id_middle_container">
						<div class="text" id="id_text">Edit</div>
					</div>
		  		</div>
		  		<form class="form-signin" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
		  			<input class="d-none" type="file" name="image" id="id_profile_image" onchange="readURL(this)">
			  		<h6 class="mt-4 field-heading">Nick Name</h6>
			  		<input type="text" name="nick_name" id="id_input_username" class="form-control" placeholder="Nickname" required
					value="{{form.initial.nick_name}}">
					<div class="mt-4 checkbox">
						<label>
							<input type="checkbox" name="hide_email" id="id_input_hide_email" {% if form.initial.hide_email %}checked{%endif%}>
							Hide Email
						</label>
			  			
					</div>

					{% for field in form %}
					<p>
					{% for error in field.errors %}
					<p style="color: red">{{ error }}</p>
					{% endfor %}
					</p>
					{% endfor %}
					{% if form.non_field_errors %}
					<div style="color: red">
					<p>{{form.non_field_errors}}</p>
					</div>

					{% endif %}

					<div class="d-flex flex-column mt-4">
						<button class="mt-4 btn btn-primary flex-grow-1" type="submit">Save</button>
					</div>
					
				</form>

		  	</div>
		  </div>
		</div>
	</div>
</div>


<script type="text/javascript">

	var cropper;
	var imageFile;
	var base64ImageString;
	var cropX;
	var cropX;
	var cropWidth;
	var cropHeight;

	enableImageOverlay()

	function enableImageOverlay(){
		var text = document.getElementById("id_text")
		text.style.backgroundColor = "#0066ff"
		text.style.color = "white"
		text.style.fontSize = "16px"
		text.style.padding = "16px 32px"
		text.style.cursor = "pointer"

		var profileImage = document.getElementById("id_profile_image")
		profileImage.style.opacity = "1"
		profileImage.style.display = "block"
		profileImage.style.width = "100%"
		profileImage.style.height = "auto"
		profileImage.style.transition = ".5s ease"
		profileImage.style.backfaceVisibility  = "hidden"
		profileImage.style.cursor = "pointer"

		var middleContainer = document.getElementById("id_middle_container")
		middleContainer.style.transition = ".5s ease"
		middleContainer.style.opacity = "0"
		middleContainer.style.position = "absolute"
		middleContainer.style.top = "50%"
		middleContainer.style.left = "50%"
		middleContainer.style.transform = "translate(-50%, -50%)"
		middleContainer.style.textAlign = "center"

		var imageContainer = document.getElementById("id_image_container")
		imageContainer.addEventListener("mouseover", function( event ) { 
			profileImage.style.opacity = "0.3"
			middleContainer.style.opacity = "1"
		})

		imageContainer.addEventListener("mouseout", function( event ) { 
			profileImage.style.opacity = "1"
			middleContainer.style.opacity = "0"
		})

		imageContainer.addEventListener("click", function(event){
			document.getElementById('id_profile_image').click();
		});

		var cropConfirm = document.getElementById("id_image_crop_confirm")
		cropConfirm.classList.remove("d-flex")
		cropConfirm.classList.remove("flex-row")
		cropConfirm.classList.remove("justify-content-between")
		cropConfirm.classList.add("d-none")
		
	}

	function disableImageOverlay(){
		var profileImage = document.getElementById("id_profile_image_display")
		var middleContainer = document.getElementById("id_middle_container")
		var imageContainer = document.getElementById("id_image_container")
		var text = document.getElementById("id_text")

		imageContainer.removeEventListener("mouseover", function( event ) { 
			profileImage.style.opacity = "0.3"
			middleContainer.style.opacity = "1"
		})

		imageContainer.removeEventListener("mouseout", function( event ) { 
			profileImage.style.opacity = "1"
			middleContainer.style.opacity = "0"
		})

		profileImage.style.opacity = "1"
		middleContainer.style.opacity = "0"
		text.style.cursor = "default"
		text.style.opacity = "0"

		document.getElementById('id_image_container').removeEventListener("click", function(event){
			event.preventDefault();
			// do nothing
		});
		document.getElementById('id_profile_image').addEventListener("click", function(event){
			event.preventDefault();
			// do nothing
		});

		var cropConfirm = document.getElementById("id_image_crop_confirm")
		cropConfirm.classList.remove("d-none")
		cropConfirm.classList.add("d-flex")
		cropConfirm.classList.add("flex-row")
		cropConfirm.classList.add("justify-content-between")

		var confirm = document.getElementById("id_confirm")
		confirm.addEventListener("click", function(event){
			console.log("Sending crop data for processing...")
			cropImage(
				imageFile, 
				cropX, 
				cropY, 
				cropWidth,
				cropHeight
			)
		})

		var cancel = document.getElementById("id_cancel")
		cancel.addEventListener("click", function(event){
			console.log("Reloading window...")
			window.location.reload();
		})
	}

	/* return null if invalid or base64String if valid */
	function isImageSizeValid(image){
		console.log("max size: {{DATA_UPLOAD_MAX_MEMORY_SIZE}}")
		// console.log(image)
		var startIndex = image.indexOf("base64,") + 7;
		var base64str = image.substr(startIndex);
		var decoded = atob(base64str);
		console.log("FileSize: " + decoded.length);
		if(decoded.length>= "{{DATA_UPLOAD_MAX_MEMORY_SIZE}}"){
			return null
		}
		return base64str
	}

	function cropImage(image, x, y, width, height){
		base64ImageString = isImageSizeValid(image)

		if(base64ImageString != null){
			var requestData = {
				"csrfmiddlewaretoken": "{{ csrf_token }}",
				"image": base64ImageString,
				"cropX": cropX,
				"cropY": cropY,
				"cropWidth": cropWidth,
				"cropHeight": cropHeight
			}
			displayLoadingSpinner(true)
			$.ajax({
				type: 'POST',
				dataType: "json",
				{% comment %} url: "{% url 'account:crop_image' user_id=form.initial.id %}", {% endcomment %}
				data: requestData,
				timeout: 10000,
				success: function(data) {
					if(data.result == "success"){
						document.getElementById("id_cancel").click()
					}
					else if(data.result == "error"){
						alert(data.exception)
						document.getElementById("id_cancel").click()
					}
				},
				error: function(data) {
					console.error("ERROR...", data)
				},
				complete: function(data){
					displayLoadingSpinner(false)
				}
			});
		}
		else{
			alert("Upload an image smaller than 10 MB");
			document.getElementById("id_cancel").click()
		}
	}

	/*
		Called when a new image is selected from file chooser dialog
	*/
	function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
            	disableImageOverlay()
            	var image = e.target.result
            	var imageField = document.getElementById('id_profile_image_display')
                imageField.src = image
				cropper = new Cropper(imageField, {
					aspectRatio: 1/1,
					crop(event) {
						// console.log("CROP START")
						// console.log("x: " + event.detail.x);
						// console.log("y: " + event.detail.y);
						// console.log("width: " + event.detail.width);
						// console.log("height: " + event.detail.height);
						setImageCropProperties(
							image,
							event.detail.x,
							event.detail.y,
							event.detail.width,
							event.detail.height
						)
					},
				});
            };
            reader.readAsDataURL(input.files[0]);
        }
    };

    function setImageCropProperties(image, x, y, width, height){
		imageFile = image
		cropX = x
		cropY = y
		cropWidth = width
		cropHeight = height
	}

</script>



{% endblock content %}

users/templates/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style type="text/css">
    .card {
        /* Add shadows to create the "card" effect */
        box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        transition: 0.3s;
    }
    
    /* On mouse-over, add a deeper shadow */
    .card:hover {
        box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
    }
    
    /* Add some padding inside the card container */
    .container {
        padding: 2px 16px;
    }

</style>

<div class="card">
    <img class="rounded" src="{{profile_image}}" alt="Avatar">
    <div class="container">
        <h4><b>{{username}}</b></h4>
        {% if is_self %}
        <h5>{{email}}</h5>
        {% else %}
            {% if hide_email %}
                <h5>************</h5>
            {% else %}
                <h5>{{email}}</h5>
            {% endif %}
        {% endif %}
        <!-- If Auth user is viewing their own profile -->
        {% if is_self %}
        <a href="{% url 'profile:edit' username=request.user %}">update</a>
        {% endif %}
    </div>
</div>
{% endblock content %}