core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
# from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
	path('accounts/', include('allauth.urls')),
	path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('profile/', include('users.urls', namespace='profile')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


users/urls.py
from django.urls import path
from users.views import (
    profile_view,
    edit_profile_view,
)

app_name = 'users'

urlpatterns = [
    path('<username>/',profile_view, name="view"),
    path('<username>/edit/',edit_profile_view, name="edit"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django-allauth tutorial</title>
</head>

<link rel="stylesheet" href="{% static 'css/style.css' %}">

<body>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load socialaccount %}
{% block content %}

    {% if request.user.is_authenticated %}
        <h1>Hi</j1>
        <h1>
        <a href="{% url 'profile:view' username=request.user.username %}">{{ request.user.username }}</a>
        <a href="{% url 'profile:view' username=request.user.username %}?JSON=True">JSON</a>
        </h1>
        <img class="rounded" src=".{{ request.user.profile.image.url }}">
       
    
        <a href="{% url 'account_logout' %}">Logout</a>

    {% else %}

        <h1>Not logged in</h1>

        <a class="btn" href="{% url 'account_login' %}">Login</a>
        {% comment %} <a class="btn" href="{% provider_login_url 'provider' %}">42 Login</a> {% endcomment %}
		<a href="{% provider_login_url 'fourtytwo' %}">42 Login</a>

    {% endif %}

{% endblock content %}


templates/home2.html
{% load socialaccount %}

<h1>Web App with OAuth2 Log In </h1>

{% if user.is_authenticated %}

<p>Welcome {{ user.email }}, you just logged in via your instance!</p>

    <form method="post" action="{% url 'account_logout' %}">
        {% csrf_token %}
        <button type="submit">Log Out</button>
    </form>

{% else %}

    <p>Click Here to log in:</p>

    <a href="{% provider_login_url 'provider' %}">Sign In</a>

{% endif %}